"""empty message

Revision ID: 30918e0d4378
Revises: 28af24917ae1
Create Date: 2022-08-30 18:24:04.721846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30918e0d4378'
down_revision = '28af24917ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
